#!/bin/bash

while true; do
clear
echo ""
echo " Please select a resolution for Xvfb :"
echo ""
echo ""
echo "1)640x480 (4:3)"
echo "2)800x600 (4:3)"
echo "3)1024x768 (4:3)"
echo "4)1280x720 (16:9)"
echo "5)1920x1080 (16:9)"
echo "6)1400x600 (7:3)"
echo "7)2560x1600 (16:10)"


echo ""
echo ""
echo ""
echo " The 1400x600 resolution manages to adapt to the proportion of the cell phone screen, to use it correctly enter the Termux-x11 settings, and in "Display resolution mode" set it to "scaled" and set it to 160%.Don't forget to set the same resolution in the Box86.conf file "
echo ""
    read -p " ..." option

    case $option in
        [1]* ) export res=640x480x24;break;;
        [2]* ) export res=800x600x24;break;;
	[3]* ) export res=1024x768x24;break;;
	[4]* ) export res=1280x720x24;break;;
	[5]* ) export res=1920x1080x24;break;;
	[6]* ) export res=1400x600x24;break;;
        [7]* ) export res=2560x1600x24;break;;
    esac
done
echo $res
DISPLAY=:1 termux-x11 &>/dev/null & env DISPLAY=:1 taskset -c 4-7 Xvfb -listen tcp :1 -ac -screen 0 $res &>/dev/null
clear
echo ""
echo ""
echo -e " Termux-x11 started at $res " 
