#!/bin/bash
DISPLAY=:1 termux-x11 &>/dev/null & env DISPLAY=:1 taskset -c 4-7 Xvfb -listen tcp :1 -ac -screen 0 1400x600x24 &>/dev/null --exit-idle-time=-1
clear
echo ""
echo ""
echo -e " Termux-x11 started "
